server:
  port: 8082

spring:
  application:
    name: user-service # Microservice name
  datasource:
    url: jdbc:mysql://auth-db983.hstgr.io:3306/u838678030_skillpro_db # Updated to remote database
    username: u838678030_skillpro_db # Remote database username
    password: Skillprodb@123 # Remote database password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # Maintain schema changes automatically
    show-sql: true # Enables SQL query logging
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # MySQL 8.x Dialect
  cloud:
    feign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Eureka server URL
