server:
  port: 8083

spring:
  application:
     name: Expertise-Service
  datasource:
    url: jdbc:mysql://localhost:3306/skillprodb
    username: root
    password: 8900
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect



# Uncomment if you are not using Eureka
#ExpertiseCategory-Service:
#  url: http://localhost:8090


