server:
  port: 9089
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://auth-db983.hstgr.io:3306/u838678030_skillpro_db
    username: u838678030_skillpro_db
    password: Skillprodb@123
  jpa:
    hibernate.ddl-auto: update
    hibernate.show_sql: true
  properties:
    hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
